### ISSUE TITLE
Features yet to be implemented

### ISSUE THREAD

**Issue by leasunhy** [leasunhy/GalaxyOJ#22]
- <del>**Contest**: Display whether a problem is solved.</del>
- <del>**Admin**: Add `modify user` page.</del>
- <del>**List**: Pagination.</del>
- <del>**Contest**: Display problem id in standing page.</del>
- <del>**Base page**: Add footer.</del>
- <del>**Editor**: Image uploading.</del>
- <del>**Security**: User input sanitizing.</del>

**Comment by leasunhy** [comment]
- <del>**UI**: Datepicker.</del>

**Comment by leasunhy** [comment]
- <del>**Admin**: Define privilege levels.</del>

**Comment by leasunhy** [comment]
**Contest**: Starting time and ending time logic. This contains:
- <del>Form validation. Ending time should be _larger_ than starting time.
- <del>Code submission. Treat submission differently based on the time when the submission happens.</del>
- <del>Problem displaying.</del>

**Comment by leasunhy** [comment]
**UI**: MathJax.

**Comment by leasunhy** [comment]
<del>**Contest**: Add existing problems.</del>

**Comment by mstczuo** [comment]
Let us leave _MathJax_ to the next version.
