### ISSUE TITLE
Judge program connot count memory usage

### ISSUE THREAD

**Issue by mstczuo** [leasunhy/GalaxyOJ#23]
It seems that the judge program wents wrong, and the memory_usage is always zero.
I'll try to fix the bug today.

**Comment by leasunhy** [comment]
Can't reproduce the bug here.
Don't forget re-compiling the judge program.

**Comment by mstczuo** [comment]
Re-compiled the judge program, but it doesn't work. The memory usage is always zero in my computer. :(
Another problem, the **syscall_used table** have to update to fix 64-bit system, or some dangerous operations are allowed such as `fork()`.

**Comment by mstczuo** [comment]
I changed `regs.rax` to `regs.orig_rax`, then the restrict functions are forbidden.

**Comment by leasunhy** [comment]
Have you tried calling `fork()` in the submitted program?
I believe this will not be a problem since the syscall tables for x86 and x64 is the same. The only difference should be the way to pass arguments.

**Comment by leasunhy** [comment]
Aha! That's pretty nice :-)

**Comment by mstczuo** [comment]
It seems that the **syscall_used** table is different in x86_64 system.
For an example, this program:

```
#include<stdio.h>
#include<unistd.h>
int main() {
    int a,b;
    scanf("%d%d", &a, &b);
    int c = fork();
    if(c == 0) {
        printf("%d\n", a + b);
    }
}
```

The program above called the system call numbers **`{ 0, 1, 5, 8, 9, 12, 56, 63, 89, 158, 231}`**, system call number 56 is **stub_clone** from _kernel/fork.c_, and a normal A+B program does not contains this call.

**Comment by leasunhy** [comment]
Yes!! The cause is just the syscall table is different!

[x86_64 syscall](http://blog.rchapman.org/post/36801038863/linux-system-call-table-for-x86-64)
[x86 syscall](http://docs.cs.up.ac.za/programming/asm/derick_tut/syscalls.html)

**Comment by leasunhy** [comment]
We need to rewrite the judge program to use x86_64 syscall table. And it should not be too difficult.
