### ISSUE TITLE
Judge program will not terminate the submitted program after time_limit is consumed

### ISSUE THREAD

**Issue by leasunhy** [leasunhy/GalaxyOJ#24]

**Comment by leasunhy** [comment]
OK, I found the cause of the bug.
It's because the judge employs `setrlimit()` syscall to set time limit for the program, and the unit used to specify the limit is `second`, while the unit used in `judge/__init__.py` is `millisecond`.
Hence it seems the judge program will not stop even after time_limit is elapsed.

**Comment by leasunhy** [comment]
Other numbers passed to the judge program might have this problem too.

**Comment by mstczuo** [comment]
Is memory limit works normally? 
I don't know why I could not display the memory usage, nevertheless we are using the same code..

**Comment by leasunhy** [comment]
No, memory usage is not affected by this issue since it does not depends on `setrlimit()` to function.
Output limit seems not affected too since the units used are identical.

**Comment by leasunhy** [comment]
Commit 066c75ec should fix this problem. It's in PR.
