### ISSUE TITLE
Online Judge Design

### ISSUE THREAD

**Issue by mstczuo** [leasunhy/GalaxyOJ#8]
## Navigation Bar

Home, Problems, Contests, Solutions, Tutorials, Status
Login/"username", Register/Logouot, Profile setting, [Add Problem, Add Contest]
## Basic Pages

Home Page: A list of post, which is labeled universal
Problem List: A list of problem
Problem Detail Page: Description of a problem
**Contest List: A list of contest**
**Contest Home Page: Display a problem list and necessary information**
**Contest Standing Page: __
Contest Status Page: Display the status of this contest
Status List: A list of all submit status.
__Rating List: A rating of all users.**
**FAQ(Help) Page: A Single post.**
**Discussion Page: A list of discussion(comments).**
## Form Pages

Register Page: A page to register``finished''
**Code Submission Page: A page to Submit codes**
Edit Post Page: A page to edit a post
## Administrating Pages

**Problem Edit Page: create or modify a problem**
**Contest Edit Page: create or modify a contest**
**User Information Edit Page: create or modify a user**
## Templates
1. Base Page: navigation bar
2. List Pages
   - List of Post
   - List of Problem
   - List of Contest
   - List of User
3. Post Page
4. Problem Page
5. Status Page
6. Contest Page
   - Contest Home
   - Contest Problem List
   - Contest Standing

**Comment by mstczuo** [comment]
All blod lines are unfinished module, let's do it together.

**Comment by leasunhy** [comment]
OK!

**Comment by mstczuo** [comment]
I'm going to implement **edit problem** page and the **code submission page**, and test the interface between server and judge.

**Comment by mstczuo** [comment]
Our first version has completed!
