### ISSUE TITLE
Database error while visiting "/tutorials"

### ISSUE THREAD

**Issue by mstczuo** [leasunhy/GalaxyOJ#9]
There are something wrong while visiting "/tutorials"

**Error Info**

> sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "tutorial" does not exist
> LINE 2: FROM post JOIN tutorial ON post.id = tutorial.id 
> 
>  [SQL: 'SELECT tutorial.id AS tutorial_id, post.id AS post_id, post.title AS post_title, post.content AS post_content, post.create_time AS post_create_time, post.type AS post_type, post.user_id AS post_user_id \nFROM post JOIN tutorial ON post.id = tutorial.id \n LIMIT %(param_1)s OFFSET %(param_2)s'] [parameters: {'param_1': 20, 'param_2': 0}]

It seems that my database needs to upgrade ?

but when I tried 

```
 python manager.py db upgrade
```

Error occurs:

```
alembic.util.CommandError: Can't locate revision identified by '7c391fa646ff'
```

**Comment by leasunhy** [comment]
You might have used the former migration scripts.
Just try rebuilding the database using:

``` bash
dropdb galaxyoj_dev
createdb galaxyoj_dev
python manager.py db upgrade
```

**Comment by mstczuo** [comment]
OK, it works.
